// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmnzddpypeqfjrbkmwac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptbnpkZHB5cGVxZmpyYmttd2FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzkxNTksImV4cCI6MjA2ODE1NTE1OX0.KEx7d1kpv_Zdx7MXuDmLXI97vXCVwdOFfaQYEfFh-Pc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});